springdoc:
  swagger-ui:
    path: /
    
spring:
  security:
    oauth2:
      client:
        registration:
          auth-service:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${JWT_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KC_REALM}
