springdoc:
  swagger-ui:
    path: /
    urls:
      - name: Auth Service
        url: /api-docs/auth-service
      - name: Account Service
        url: /api-docs/account-service
      
spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: account-service-swagger
          uri: lb://account-service
          predicates:
            - Path=/api-docs/account-service
          filters:
            - RewritePath=/api-docs/account-service, /v3/api-docs
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/auth-service
          filters:
            - RewritePath=/api-docs/auth-service, /v3/api-docs
            
