springdoc:
  swagger-ui:
    urlsPrimaryName: Auth Service
    path: /
    urls:
      - name: Auth Service
        url: /api-docs/auth-service
      - name: Account Service
        url: /api-docs/account-service
      - name: Employee Service
        url: /api-docs/employee-service
      
spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - PreserveHostHeader
        - name: AddRequestHeader
          args:
            name: Authorization
            value: "#{request.headers['Authorization']}"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - PreserveHostHeader
            # - AddRequestHeader=Authorization, $request.header.Authorization
            
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/auth-service
          filters:
            - RewritePath=/api-docs/auth-service, /v3/api-docs
            
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: account-service-swagger
          uri: lb://account-service
          predicates:
            - Path=/api-docs/account-service
          filters:
            - RewritePath=/api-docs/account-service, /v3/api-docs
            
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**,/api/v1/leaves/**,/api/v1/employee-schedules/**,/api/v1/attendances/**
        - id: employee-service-swagger
          uri: lb://employee-service
          predicates:
            - Path=/api-docs/employee-service
          filters:
            - RewritePath=/api-docs/employee-service, /v3/api-docs
            
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
