springdoc:
  swagger-ui:
    path: /
    urls:
      - name: Auth Service
        url: /api-docs/auth-service
      - name: Account Service
        url: /api-docs/account-service
      
spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: account-service-swagger
          uri: lb://account-service
          predicates:
            - Path=/api-docs/account-service
          filters:
            - RewritePath=/api-docs/account-service, /v3/api-docs
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=Authorization, $request.header.Authorization
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/auth-service
          filters:
            - RewritePath=/api-docs/auth-service, /v3/api-docs
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
